name: the_movie_db_api
description: A remote implementation of The Movie DB
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.10
  coverage: ^1.1.0
  freezed: ^2.0.2
  json_serializable: ^6.1.6
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
dependencies:
  dio: ^4.0.6
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
